### ISSUE TITLE
Remove console printouts

### ISSUE THREAD

**Issue by masonlouchart** [reinert/dygraph-elements#1]
There are still some warnings and info console around the [line 52](https://github.com/reinert/dygraph-elements/blob/master/dygraph-line.html#L52-L54).

**Comment by reinert** [comment]
I let those because I'm the only user yet.

But I can remove it.

There are still many features I would like to implement but have no time.

If you're planning to use, feel free to contribute.

**Comment by masonlouchart** [comment]
In fact I started to use Dygraphs a week ago and I thought to implement a Polymer element so... I think contribute a bit. I'm surprised do not have found your wrap earlier.

**Comment by masonlouchart** [comment]
@reinert please could you review the related PR ?
